[package]
name = "zxibs/wrapperservice"
description = "This service allows you to create custom properties for roblox instances, see the documentation for more info: https://zxibs.github.io/WrapperServiceService/ github: https://github.com/zxibs/WrapperServiceService"
version = "0.4.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["LICENSE.md", "README.md", "src", "src/**", "wally.toml", "default.project.json"]

[dependencies]
